---
title: "modibo_report"
format: dashboard
---

```{r}
library(ggplot2)
library(readxl)

lfstudy_participant <- read_excel("C:/Users/User/Desktop/lfstudy_participant.xlsx")

```

```{r}
#Barchart
consent <-ggplot(data = lfstudy_participant,
            mapping = aes(x = consent))+
  geom_bar()+
  theme_classic()
consent

#stacked Barchart
kee_malariaTested <-ggplot(data = lfstudy_participant,
             mapping = aes(x = keea_facilities, fill = malaria_t_results))+
  geom_bar()+
  theme_classic()
kee_malariaTested
#
Gomoa_malariaTested <-ggplot(data = lfstudy_participant,
             mapping = aes(x = gomoa_west_facilities, fill = malaria_t_results))+
  geom_bar()+
  theme_classic()
Gomoa_malariaTested

#Histogram
Age_MalariaPositive <-ggplot(data = lfstudy_participant,
            mapping = aes(x = age, fill = malaria_t_results))+
  geom_histogram(bins = 10, position = "dodge")+
theme_classic()  
Age_MalariaPositive

#Boxplot
Age_gender <- ggplot(data = lfstudy_participant,
               mapping = aes(x = sex, y = age,fill = malaria_t_results))+
  geom_boxplot()+
  theme_classic()
Age_gender
#=========

#Age_QFATPositive <-ggplot(data = lfstudy_participant,
#            mapping = aes(x = age, fill = qfat_test_results))+
#  geom_histogram(bins = 10, position = "dodge")+
#theme_classic()  
#Age_QFATPositive

#Histogram with dodge

```
