rm(list=ls())
gc(reset = TRUE)
#1-------------------All packages ----------------------12
library(readxl)
library(readr)
library(rio)
library(lubridate)
library(janitor)
library(here)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
library(ggsci)
library(ggpubr)
library(ggthemes)
library(skimr)
library(rstatix)
library(lessR)
library(car)
library(effsize)
library(pwr)
library(caret)
library(olsrr)
library(Hmisc)
library(plotrix)
library(survival)
library(epitools)
library(epiDisplay)
library(devtools)
library(rvest)
library(dslabs)
library(weights)
library(zoo)
library(gtools)
library(VennDiagram)
library(rafalib)
library(MASS)
library(broom)
library(gganimate)
library(matrixStats)
library(gridExtra)
library(randomForest)
library(tree)
library(splitstackshape)
library(egg)
library(rpart)
library(rpart.plot)
library(testthat)
library(scales)
library(mvtnorm)
library(deSolve)
#--------------------Importing data -------------------
library(readr)
# import white space delimited files
all_data1 <- read_table(file = 'children_data.txt', col_names = TRUE)
# import comma delimited files
all_data2 <- read_csv(file = 'children_data.csv')
# import tab delimited files
all_data3 <- read_delim(file = 'children_data.txt', delim = "\t")
# or use
all_data4 <- read_tsv(file = 'children_data.txt' )
#--------------------------------------------------
# import .csv file
child_data1 <- read.csv(file = 'children_data.csv') 
# import .csv file with dec = "," and sep = ";"
child_data2 <- read.csv2(file = 'children_data.csv')
#correct by introducing sep = ","
child_data22 <- read.csv2(file = 'children_data.csv', sep = ",")
# import tab delim file with sep = "\t"
child_data3 <- read.delim(file = 'children_data.txt')
