---
title: "LF_Study Dashboard - Noguchi Memorial Institute for Medical Research (NMIMR)"

output:
  flexdashboard::flex_dashboard:
    theme:
      bg: "#E0EEEE"
      fg: "#104E8B"
      primary: "#1874CD"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
#---------------------------------------------------
#Import Packages
library(flexdashboard)
library(knitr)
library(rsconnect)
library(readxl)
library(readr)
library(tidyverse)
library(rpivotTable)
library(ggplot2)
library(plotly)
library(dplyr)
library(patchwork)
library(openintro)
library(highcharter)
library(gtsummary)
library(DT)
library(gt)
#
```



```{r}
#Import Data

LFdata <- read_excel("LF_Aug_5.xlsx")
#

df <- LFdata %>% mutate(Age_group = case_when(
  age < 10 ~ "<10",
  age >= 10 & age <= 19 ~ "10-19",
  age >= 20 & age <= 29 ~ "20-29",
  age >= 30 & age <= 40 ~ "30-40",
  age > 40 ~ ">40",
  TRUE ~ NA_character_))

```

Row 
---------------------------------
###

```{r}
library(gtsummary)
# Basic Info

# Consent summary
consent_sum <- LFdata %>%
  count(consent)

# Total records
total_records <- nrow(LFdata)

# Total consent = Yes
consent_yes <- consent_sum %>%
  filter(consent == "Yes") %>%
  pull(n)

if (length(consent_yes) == 0) consent_yes <- 0

# Consent rate
consent_rate <- round(
  100 * consent_yes / sum(consent_sum$n),
  1
)

# Gauge chart
plot_ly(
  type = "indicator",
  mode = "gauge+number",
  value = consent_rate,
  number = list(suffix = "%"),
  gauge = list(
    axis = list(range = list(0, 100)),
    bar = list(color = "#FFF3CD"),
    bgcolor = "white",
    borderwidth = 1,
    bordercolor = "grey",
    steps = list(
      list(range = c(0, 50), color = "#EE6363"),
      list(range = c(50, 80), color = "#4CAF50"),
      list(range = c(80, 100), color = "#4CAF50")
    ),
    threshold = list(
      line = list(color = "red", width = 2),
      thickness = 0.15,
      value = consent_rate
    )
  )
) %>%
  layout(
    margin = list(l = 150, t = 20, b = 70),
    annotations = list(
      
      # Bottom title
      list(
        text = "<b>Overall Consent Rate</b>",
        x = 0.5,
        y = -0.15,
        xref = "paper",
        yref = "paper",
        showarrow = FALSE,
        font = list(size = 16)
      ),
      
      # Left information panel
      list(
        text = paste0(
          "<b>Total Records</b><br>",
          total_records,
          "<br><br>",
          "<b>Consent = Yes</b><br>",
          consent_yes
        ),
        x = -0.80,
        y = 0.5,
        xref = "paper",
        yref = "paper",
        showarrow = FALSE,
        align = "center",
        font = list(
          size = 15,
          color = "#555555"
        )
      )
    )
  )

```

###

```{r}
# Study site summary
site_sum <- LFdata %>%
  count(site) %>%
  mutate(
    Percent = round(100 * n / sum(n), 1)
  )

# Pie chart
plot_ly(
  data = site_sum,
  labels = ~site,
  values = ~n,
  type = "pie",
  textinfo = "label+percent",
  textposition = "inside",
  hovertemplate = paste(
    "<b>%{label}</b><br>",
    "Participants: %{value}<br>",
    "Percentage: %{percent}<extra></extra>"
  ),
  marker = list(
    colors = c("#4CAF50", "#FF9800", "#3F51B5", "#CD3333")
  ),
  showlegend = TRUE
) %>%
  layout(
    title = list(
      text = "<b>Study Site Distribution</b>",
      x = 0.8
    )
  )
```

###

```{r}
# Create summary table
malaria_plot <- bind_rows(
  df %>%
    count(Response = malaria_test_done) %>%
    mutate(Variable = "Malaria test done"),

  df %>%
    count(Response = malaria_t_results) %>%
    mutate(Variable = "Malaria test result")
) %>%
  group_by(Variable) %>%
  mutate(
    Percent = round(100 * n / sum(n), 1)
  ) %>%
  ungroup()

# Interactive stacked bar chart
plot_ly(
  data = malaria_plot,
  x = ~Variable,
  y = ~n,
  color = ~Response,
  colors = c("#4CAF50", "#FF9800", "#3F51B5", "#CD3333"),
  type = "bar",
  textposition = "none",
  customdata = ~Percent,
  hovertemplate = paste(
    "<b>%{fullData.name}</b><br>",
    "Count: %{y}<br>",
    "Percentage: %{customdata}%<extra></extra>"
  )
) %>%
  layout(
    title = "<b>Malaria Testing Results</b>",
    barmode = "stack",
    hovermode = "x unified",
    xaxis = list(title = ""),
    yaxis = list(title = "Number of Participants"),
    legend = list(
      title = list(text = "Response")
    )
  )

```

###

```{r}


# Create summary data
fts_plot <- bind_rows(

  df %>%
    count(Response = fts_test_done) %>%
    mutate(Variable = "FTS test done"),

  df %>%
    count(Response = fts_test_result) %>%
    mutate(Variable = "FTS test result")

) %>%
  group_by(Variable) %>%
  mutate(
    Percent = round(100 * n / sum(n), 1)
  ) %>%
  ungroup()

# Interactive stacked bar chart
plot_ly(
  data = fts_plot,
  x = ~Variable,
  y = ~n,
  color = ~Response,
  colors = c("#4CAF50", "#FF9800", "#3F51B5", "#A52A2A"),
  type = "bar",
  textposition = "none",
  customdata = ~Percent,
  hovertemplate = paste(
    "<b>%{fullData.name}</b><br>",
    "Count: %{y}<br>",
    "Percentage: %{customdata}%<extra></extra>"
  )
) %>%
  layout(
    title = "<b>FTS Testing Results</b>",
    barmode = "stack",
    hovermode = "x unified",   # <- Compare all responses on hover
    xaxis = list(title = ""),
    yaxis = list(title = "Number of Participants"),
    legend = list(
      title = list(text = "Response")
    )
  )
```


Row
-------------------------------------------------------------------------------
###                                              KEEA_Municipal - Malaria & QFAT 
  
```{r}
#KEEA_Municipal
community_table <- LFdata %>%
  filter(site != "Gomoa West District") %>%
  group_by(site, keea_communities, keea_facilities) %>%
  summarise(
    Malaria_Tested = n(),
    Malaria_Positives = sum(malaria_t_results == "Positive", na.rm = TRUE),
    Malaria_Pct = paste0(round(100 * Malaria_Positives / Malaria_Tested, 1), "%"),
    FTS_Tested = sum(!is.na(fts_test_result)),
    FTS_Positives = sum(fts_test_result == "Positive", na.rm = TRUE),
    FTS_Pct = paste0(round(100 * FTS_Positives / FTS_Tested, 1), "%"),
    .groups = "drop"
  ) %>%
  select(
    site,
    keea_communities,
    keea_facilities,
    Malaria_Tested,
    Malaria_Positives,
    Malaria_Pct,
    FTS_Tested,
    FTS_Positives,
    FTS_Pct
  ) %>%
  arrange(desc(FTS_Positives))

kable(community_table, align = "c")

```        

Row
------------------------------------------------------------------------------
###                                           Gomoa.West_District-Malaria & QFAT 
  
```{r}
#Gomoa.West_District
community_table <- LFdata %>%
  filter(site != "KEEA-Municipal") %>%
  group_by(site, gomoa_west_communities, gomoa_west_facilities) %>%
  summarise(
    Malaria_Tested = n(),
    Malaria_Positives = sum(malaria_t_results == "Positive", na.rm = TRUE),
    Malaria_Pct = paste0(round(100 * Malaria_Positives / Malaria_Tested, 1), "%"),
    FTS_Tested = sum(!is.na(fts_test_result)),
    FTS_Positives = sum(fts_test_result == "Positive", na.rm = TRUE),
    FTS_Pct = paste0(round(100 * FTS_Positives / FTS_Tested, 1), "%"),
    .groups = "drop"
  ) %>%
  select(
    site,
    gomoa_west_communities,
    gomoa_west_facilities,
    Malaria_Tested,
    Malaria_Positives,
    Malaria_Pct,
    FTS_Tested,
    FTS_Positives,
    FTS_Pct
  ) %>%
  arrange(desc(FTS_Positives))

kable(community_table, align = "c")

```