---
title: "my_workflow"
author: "Modibo"
date: "2025-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r cars}
#:::::::::::::::::::::::::::::::::import data :::::::::::::::::::::::::::::::::#
rm(list=ls())
gc(reset = TRUE)
#all file types
library(rio)
#import("C:/Users/User/Desktop/repos/NNJ.csv") ---------------------

library(readr)
library(readxl)
imdata <- read_excel("C:/Users/User/Desktop/repos/immunoData.xlsx")
View(imdata)
HTdata <- read_excel("C:/Users/User/Desktop/repos/HTdata.xlsx")
View(HTdata)
library(skimr)
skim_without_charts(imdata)

#:::::::::::::::::::::::::::: Data manipulations:::::::::::::::::::::::::::::::#
library(tidyverse)
library(dplyr)
data2 <- imdata %>%
  select(CaseControl, expose, age,delivage, hb, plt, parity, bmi ) %>% 
  filter(hb > 10)        
print(data2)
# Finding rows with NA value
with_na <- data2 %>% filter(is.na(hb)) 
print(with_na)
  # Finding rows with no NA value
without_na <- data2 %>% filter(!is.na(hb)) 
print(without_na)
# arrange data by age 
data_frm <- data2 %>% filter(!is.na(hb)) %>% 
arrange(desc(age)) 
print(data_frm)           
# Calculating a variable- / create New variables
mutate(data_frm, RBC = hb/3)
mutate(data_frm, HCT = hb*3)
# print-(only new column)
transmute(data_frm,hb,HCT = hb*3, RBC = hb/3) 
##rename 
rename(data_frm,Delivr_age = delivage, Bmi = bmi)
#summaries
summarise(data_frm,mean_hb = mean(hb))  
summarise(data_frm,median_hb = median(hb))

#:::::::::::::::::::::::::::: reshape with tidyr :::::::::::::::::::::::::::::##
library(tidyr) 
HTdata <- read_excel("C:/Users/User/Desktop/repos/HTdata.xlsx")
print(HTdata)

 # use gather()function to make data longer
long <- HTdata %>%  
  gather(fullName, Frequency, 
         first_trimester, second_trimester, third_trimester)
print(long)

# use separate()function 
separate_data <- long %>%  
  separate(fullName, c("firstName","secondName"))
separate_data

# use unite() function 
unite_data <- separate_data %>%  
  unite(fullName, firstName, secondName, sep = " ") 
unite_data

# use pivot()function--------------------------------------------------- 
ldata <- pivot_longer(
  data = HTdata,
  cols = c(first_trimester, second_trimester, third_trimester),
  names_to = "trimester1",
  values_to = "value"
)
View(ldata)
#----------------------                                 ----------------
wdata <- pivot_wider(
  data = ldata,
  names_from = "trimester1",
  values_from = "value",
)
View(wdata)
#-----------------------------------------------------------------------
#:::::::::::::::::::::: Visualization with ggplot2 ::::::::::::::::::::::::::#
library(ggplot2)
library(RColorBrewer)
library(readxl)
 imdata <- read_excel("C:/Users/User/Desktop/repos/immunoData.xlsx")
 View(imdata)
#plotting points 
immu <- ggplot(data = imdata,
              mapping = aes(x = systol1, y = diastol1, colour = CaseControl, shape = expose))+
   geom_point()+theme_classic()
immu
#creating density plot 
immu1 <- ggplot(data = imdata,
               mapping = aes(x = diastol1, colour = CaseControl))+
  geom_density()
immu1
#point and smoothing
immu2 <- ggplot(data = imdata,
               mapping = aes(x = bmi, y = plt, colour = nicu))+
  geom_smooth()+
  geom_point()
immu2

#plot jitter
immu3 <- ggplot(data = imdata,
               mapping = aes(x = systol1, y = diastol1, colour = CaseControl, shape = expose))+
  geom_jitter()
immu3

#::::::::::::::::::::::::::::::: Barchart :::::::::::::::::::::::::::::::::::#
ht <-ggplot(data = imdata,
        mapping = aes(x = expose))+
   geom_bar()
ht
#column Barchrt
ht1 <-ggplot(data = imdata,
            mapping = aes(x = expose, colour = expose, fill = expose))+
  geom_bar()
ht1
#stacked Barchart
ht2 <-ggplot(data = imdata,
            mapping = aes(x = CaseControl, fill = expose))+
  geom_bar()
ht2

#::::::::::::::::::::::::::::::: Histogram ::::::::::::::::::::::::::::::::::#
ht3 <-ggplot(data = imdata,
            mapping = aes(x = systol1))+
  geom_histogram()
ht3

#Histogram with fill
ht4 <-ggplot(data = imdata,
            mapping = aes(x = systol1, fill = expose))+
  geom_histogram()
ht4

#Histogram with stacked
ht <-ggplot(data = imdata,
            mapping = aes(x = systol1, fill = expose))+
  geom_histogram(bins = 10, position = "stack")
ht

#Histogram with dodge
ht <-ggplot(data = imdata,
            mapping = aes(x = systol1, fill = expose))+
  geom_histogram(bins = 10, position = "dodge")
ht
#-----------------Viridis------------------------------
hh <-ggplot(data = imdata,
            mapping = aes(x = systol1, fill = expose))+
  geom_histogram(bins = 10, position = "dodge")
hh + scale_fill_viridis_d()
hh + scale_fill_viridis_d(direction = -1)
hh
#::::::::::::::::::::::::::::::: Boxplot:::::::::::::::::::::::::::::::::::::#
immu <- ggplot(data = imdata,
               mapping = aes(x = systol1, y = diastol1))+
  geom_boxplot()
immu
# Boxplot by category ##
immu <- ggplot(data = imdata,
               mapping = aes(x = systol1, y = diastol1, colour = expose))+
  geom_boxplot()
immu

#Boxplot with coord_flip
immu <- ggplot(data = imdata,
               mapping = aes(x = systol1, y = diastol1, colour = expose))+
  geom_boxplot()+ coord_flip()
immu

#plotting by factor
immu <- ggplot(data = imdata,
               mapping = aes(x = systol1, y = diastol1))+
  geom_boxplot(aes(fill = factor(nicu)))
immu

# Violin chart 
immu <- ggplot(data = imdata,
               mapping = aes(x = systol1, y = diastol1, colour = expose))+
  geom_violin()
immu 
dd <- immu +scale_x_log10()+
dd

# Facet wrap 
immwrp <- ggplot(data = imdata,
               mapping = aes(x = systol1, y = diastol1, colour = grvdty))+
  geom_violin()+
  facet_wrap(~expose)
immwrp

# Facet grid
immgrd <- ggplot(data = imdata,
                mapping = aes(x = systol1, y = diastol1, colour = grvdty))+
  geom_violin()+
  facet_grid(CaseControl~expose)
immgrd

#:::::::::::::::::::::::::::::: Label & Annotation :::::::::::::::::::::::::#
immuLAB <- ggplot(data = imdata)+
  geom_point(mapping = aes(x = systol1, y = diastol1, colour = CaseControl, shape = expose))+
  labs(title ="Immunoassay Data", subtitle = "ImmunoAnalysis",caption = "Data collection by Mohammed")+
  annotate( "text",x = 145,y = 90, label ="Malaria in pregnancy                              ", color ="purple",
           fontface ="bold", size =4.0,angle = 30)
immuLAB
#  Alternative
immuLAB <- ggplot(data = imdata)+
  geom_point(mapping = aes(x = systol1, y = diastol1, colour = CaseControl, shape = expose))+
  labs(title ="Immunoassay Data", subtitle = "ImmunoAnalysis",caption = "Data collection by Mohammed")+
  annotate( "text",x = 145,y = 90, label ="Malaria in pregnancy                              ", color ="purple",
            fontface ="bold", size =4.0,angle = 30)+
  theme_classic()
immuLAB
#------------------------Viridis---------------------
immuLAB <- ggplot(data = imdata)+
  geom_point(mapping = aes(x = systol1, y = diastol1, colour = expose))+
  labs(title ="Immunoassay Data", subtitle = "ImmunoAnalysis",caption = "Data collection by Mohammed")+
  annotate( "text",x = 145,y = 90, label ="Malaria in pregnancy                              ", color ="purple",
            fontface ="bold", size =4.0,angle = 30)+
  theme_classic()+scale_colour_viridis_d()
immuLAB
#--------------viridis(City\nCenter)----------------
immuLAB <- ggplot(data = imdata)+
  geom_point(mapping = aes(x = systol1, y = diastol1, colour = expose))+
  labs(title ="Immunoassay Data", subtitle = "ImmunoAnalysis",caption = "Data collection by Mohammed")+
  annotate( "text",x = 145,y = 90, label ="Malaria in pregnancy                              ", color ="purple",
            fontface ="bold", size =4.0,angle = 30)+
  theme_classic()+scale_colour_viridis_d(option = "City\nCenter")
immuLAB
# Save plot 
ggsave("immuLAB.png")

#::::::::::::::::::::: Pie-charts & Bar-chart :::::::::::::::::::::::::::#
library(lessR)
imm2 <- rd("C:/Users/User/Desktop/repos/immunoData.xlsx")

# Piechart
PieChart(expose, data = imm2,
         hole = 0,
         main = NULL)
# Donut chart
imm3 <- rd("C:/Users/User/Desktop/repos/immunoData.xlsx")
PieChart(expose, data = imm3,
         fill = "viridis",
         main = NULL,
         color = "black",
         lwd = 1.5,
         values_color = c(rep("white", 4), 1),
         values_size = 0.85)
# Donut chart
data1 <- rd("C:/Users/User/Desktop/repos/immunoData.xlsx")
PieChart(expose, data = data1,
         fill = "blues",
         hole_fill = "#B7E3E0",
         main = NULL)

# Barchart
imm4 <- rd("C:/Users/User/Desktop/repos/immunoData.xlsx")
BarChart(expose, data = imm4,
         fill = "blues",
         hole_fill = "#B7E3E0",
         main = NULL)

data <- rd("C:/Users/User/Desktop/repos/immunoData.xlsx")
BarChart(expose, data = data,
         fill = "reds",
         hole_fill = "#B7E3E0",
         main = NULL)

data <- rd("C:/Users/User/Desktop/repos/immunoData.xlsx")
BarChart(expose, data = data,
         fill = "viridis",
         main = NULL,
         color = "black",
         lwd = 1.5,
         values_color = c(rep("white", 4), 1),
         values_size = 0.85)

# slant x labels (45 angle)
BarChart(expose, data = data,
         fill = "viridis",
         main = NULL,
         color = "black",
         lwd = 1.5,
         rotate_x=45,
         values_color = c(rep("white", 4), 1),
         values_size = 0.85)

#::::::::::: sample size ::
library(pwr)
sample1 <- power.t.test(delta = 0.2, sd = 0.5, power = 0.99, type = "two.sample")
sample1

#::::::::::: categorical descriptive :::::::::::::# 
#aggregate data
library(janitor)
library(readxl)
imdata3 <- read_excel("C:/Users/User/Desktop/repos/immunoData.xlsx")
print(imdata3)
imdata3 %>%
  tabyl(hb, sex) %>%
  adorn_totals(where = "row") %>%
  adorn_percentages(denominator = "col") %>%
  adorn_pct_formatting() %>%
  adorn_ns(position = "front") %>%
  adorn_title(
    row_name = "Hgb",
    col_name = "Gender",
    placement = "combined") %>% 
  flextable::flextable() %>% 
  flextable::autofit()

# fisher exact test:
tab <- tabyl(imdata3, mode, nicu)
fisher.test(tab)
# Chi-square test::
tab <- tabyl(imdata3, mode, nicu)
chisq.test(tab)

chisq.test(tab)$residuals

#:::::::::::::::::::::::::::::: Statistics ::::::::::::::::::::::::::#
library(rstatix)

library(car)
#:::correlation matrix::::
library(Hmisc)
library(plotrix)

#:::::::::::::::::::: regress and model building::::::::::::::::::::#
library(car)
summary(microbes)
model <- lm(Occupation ~ No.of.births, data = microbes)
summary(model)
plot(microbes$No.of.births, microbes$Onset.of.labour)
abline(model)
# Plot residuals against the fitted values
residualPlots(model)
# Perform anova on the model
anova(model)

library(olsrr)


#--------------------- Time Series Analysis ----------------------------------#

#Typical Questions__when is consumption highest / lowest
                 #__variation with season
                 #__trends
                 #__change overtime.
library(readxl)
TTdata <- read_excel("C:/Users/User/Desktop/repos/CTrends.xlsx")
View(TTdata)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(RColorBrewer)





######################### Mapping with r ######################################

install.packages("sf")
library(tidyverse)
library(mapview)
library(sf)
```
