---
title: "SPOT Interns"
author: "Mohammed Yussif -Data Manager"
date: "2025-08-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
gc(reset = TRUE)
#--------------------------- required packages
library(readxl)
library(readr)
library(tidyverse)
library(RColorBrewer)
library(ggpubr)
library(psych)
library(car)
library(lessR)
library(plotrix)
library(FSA)
library(Hmisc)


#---------------------------- Import functions 
#set directorate 
setwd("C:/Users/User/Desktop")
ghsdata <- read_excel("yussif.xlsx")

library(readr)
csv <- read_csv("yussif.csv")
#simply---------------------
library(readxl)
ghsdata <- read_excel("C:/Users/User/Desktop/yussif.xlsx")

View(ghsdata)
print(ghsdata)

#  #  #--------------------- Working with dplyr
library(dplyr)
# Remove the 'Apgar1min' column

ghsdata1 <- ghsdata1 %>% select(-Apgar1min)
print(ghsdata1)
#Remove multiple columns
ghsdata1 <- ghsdata1 %>% select(-c(Age, Gender))
#  #  #
#--------------------------- Data Conversion 

library(ggplot2)
library(RColorBrewer)
library(plotrix)
library(readxl)
str(ghsdata1)
ghsdata1$Age <-as.integer(ghsdata1$Age)
ghsdata1$Gravidity <- as.integer(ghsdata1$Gravidity)
ghsdata1$Parity <- as.integer(ghsdata1$Parity)
ghsdata1$Status <-factor(ghsdata1$Status,
                                  levels = c(1,2),
                                  labels = c("control", "case"))

ghsdata1$Babysex <-factor(ghsdata1$Babysex,
                          levels = c(1,2),
                          labels = c("Male", "Female"))

ghsdata1$ModeOfDelivery <-factor(ghsdata1$ModeOfDelivery,
                        levels = c(1,2),
                        labels = c("Vaginal", "Caesarean"))

ghsdata1$bld_grp <-factor(ghsdata1$bld_grp,
                            levels = c(1,2,3,4),
                            labels = c("A positive", "B positive", "AB positive", "O positive"))
str(ghsdata1)
print(ghsdata1)
#   #   #


#---------------------------- Explore data                                   
#Missing Data Summary
summary(ghsdata1)

# Count missing values in each column
missing_per_column <- colSums(is.na(ghsdata1))
print(missing_per_column)

# Remove rows with any missing values 
cleaned_data <- na.omit(ghsdata1)
print(cleaned_data)

verify_missing <- colSums(is.na(cleaned_data))
print(verify_missing)

#  #  # 
#--------------------- Data Transformation 

library(psych)
library(readxl)

skew(ghsdata1$Age, na.rm = TRUE)
kurtosi(ghsdata1$Age, na.rm = TRUE)


lg_data <-log(imdata$systol1)
hist(lg_data)

#-----------------Confidence interval of the mean
t.test(ghsdata1$Age,
       conf.level=0.95)         

#   #   #
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                            Descriptive statistics                            

library(psych)
summary(ghsdata1)
describe(ghsdata1$Age)

summary(imdata$bwgt)
describe(imdata$bwgt)

Histogram
hist(ghsdata1$Age, col="gray", main="NCD for pregnant women", xlab="Birthweight")

#   #   #

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                        TEST OF ONE / TWO SAMPLES                                                
  
library(psych)
library(readxl) 
library(lessR)

amdata <- read_excel("ARMdata.xlsx")
print(amdata)  
describe(amdata)  
#-----------------One sample t-test
observed    = Data$Age
theoretical = 40
hist(Data$ Angle, col="gray", main="Histogram of values", xlab="Angle")

t.test(observed, mu = theoretical, conf.int=0.95)

#------------------Two Samples Student’s t–test 
#paired t.test  
t.test(Value ~ Group, data=Data, var.equal=TRUE, conf.level=0.95)
#independent t.test
t.test(Value ~ Group, data=Data, var.equal=FALSE, conf.level=0.95)

# Histogram
hs<-histogram(~ age | CaseControl, col="gray",data = imdata)
hs
# Boxplot
boxplot(age ~ CaseControl, data = imdata, names=c("Case","Control"), ylab="age")

#------------- Mann–Whitney Test
wilcox.test(Value ~ Group, data=Data, exact = FALSE)
wilcox.test(Value ~ Group, data=Data)
#Box plots
boxplot(Value ~ Group, data = Data, names=c("2 pm","5 pm"), ylab="Value")

boxplot(estimated_parasitemia ~ age, data=imdata, names=c("Control","Case"), ylab="Value")

#  #  #
wilcox.test(Data$August, Data$November, paired=TRUE)
#Simple 1-to-1 plot of values
plot(Data$August, Data$November, pch = 16, xlab="August", ylab="November")
abline(0,1, col="blue", lwd=2)  

#   #   #

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#------------------------- One-way Anova using LessR -------------------option.1
#visualise statistical assumptions
library(lessR)
library(readxl)
imdata <- read_excel("ARMdata.xlsx")
print(imdata)
#normality assumption
tapply(imdata$estimated_parasitemia, imdata$age, shapiro.test)
library(car)
leveneTest(estimated_parasitemia ~ age, data=imdata)
#One-way ANOVA
ANOVA(estimated_parasitemia ~ site_name, data=imdata)
#effect size(for groups with significant)
library(effsize)
cohen.d(age ~ expose, data=subset(imdata, expose!= "non exposed"), paired=FALSE)        
cohen.d(age ~ expose, data=subset(imdata, expose!= "singleexposed"),paired=FALSE)        
#Bar charts 
age_means <- tapply(imdata$estimated_parasitemia, imdata$age,mean)

BarChart(age_means)
BarChart(age_means, values="off", bxlab = "Malaria_exposed", ylab = "Women Age")

#   #    #

  
#------------------------------- Correlation -------------------------------
  
#Pearson correlation (Parametric)
cor.test( ~ age + bmi, data=imdata, method = "pearson", conf.level = 0.95)

cor.test( ~ age + bmi, data=imdata, method = "spearman", continuity = FALSE, conf.level = 0.95)
  
  #   #   #
  
  
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                           Regression analysis                                +

  model = lm(Species ~ Latitude, data = Data)
  summary(model)                    
  
  #    #    #   
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                           LOGISTIC REGRESSION                                +

#--------------------------- Simple Logistic Regression 
logistic <- glm(CaseControl ~ age, data = imdata, family = "binomial" )
summary(logistic)
exp(0.05512)
exp(coef(logistic))

#----------------------- Multiple Logistics regression 
multi_logist <- glm(CaseControl ~ age + bmi + parity, data = imdata, family = "binomial" )
summary(multi_logist)


#   #   #
  
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                          Chisquare                                           +
  
imdata <- read_excel("immunoData.xlsx")
#chisquare
table(imdata$CaseControl,imdata$sex)
chisq.test(imdata$CaseControl,imdata$sex)

```
